### ISSUE TITLE
Mission build/assets/js directory 

### ISSUE THREAD

**Issue by jeregrine** [phoenixframework/phoenix_site#2]
- Clone repo
- `mix deps.get`
- `mix obelisk build`
```
➜  phoenix_site git:(master) mix obelisk build
** (File.Error) could not list directory "./build/assets/js": no such file or directory
    (elixir) lib/file.ex:1306: File.ls!/1
    lib/obelisk/assets.ex:14: Obelisk.Assets.js_files/0
    lib/obelisk/assets.ex:27: Obelisk.Assets.js/0
    lib/obelisk/document.ex:17: Obelisk.Document.prepare/2
    lib/obelisk/page.ex:11: Obelisk.Page.prepare/2
    (elixir) lib/enum.ex:675: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:675: Enum.each/2
    lib/obelisk/tasks/build.ex:19: Obelisk.Tasks.Build.run/1

16:35:54.321 [error] GenServer Obelisk.Supervisor terminating
** (File.Error) could not list directory "./build/assets/js": no such file or directory
    (elixir) lib/file.ex:1306: File.ls!/1
    lib/obelisk/assets.ex:14: Obelisk.Assets.js_files/0
    lib/obelisk/assets.ex:27: Obelisk.Assets.js/0
    lib/obelisk/document.ex:17: Obelisk.Document.prepare/2
    lib/obelisk/page.ex:11: Obelisk.Page.prepare/2
    (elixir) lib/enum.ex:675: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:675: Enum.each/2
    lib/obelisk/tasks/build.ex:19: Obelisk.Tasks.Build.run/1
Last message: {:EXIT, #PID<0.73.0>, {%File.Error{action: "list directory", path: "./build/assets/js", reason: :enoent}, [{File, :ls!, 1, [file: 'lib/file.ex', line: 1306]}, {Obelisk.Assets, :js_files, 0, [file: 'lib/obelisk/assets.ex', line: 14]}, {Obelisk.Assets, :js, 0, [file: 'lib/obelisk/assets.ex', line: 27]}, {Obelisk.Document, :prepare, 2, [file: 'lib/obelisk/document.ex', line: 17]}, {Obelisk.Page, :prepare, 2, [file: 'lib/obelisk/page.ex', line: 11]}, {Enum, :"-each/2-lists^foreach/1-0-", 2, [file: 'lib/enum.ex', line: 675]}, {Enum, :each, 2, [file: 'lib/enum.ex', line: 675]}, {Obelisk.Tasks.Build, :run, 1, [file: 'lib/obelisk/tasks/build.ex', line: 19]}]}}
State: {:state, {:local, Obelisk.Supervisor}, :one_for_one, [{:child, #PID<0.159.0>, Obelisk.Config, {Obelisk.Config, :start_link, [nil]}, :permanent, 5000, :worker, [Obelisk.Config]}], :undefined, 3, 5, [], 0, Supervisor.Default, {[{Obelisk.Config, {Obelisk.Config, :start_link, [nil]}, :permanent, 5000, :worker, [Obelisk.Config]}], [strategy: :one_for_one]}}
```

And there is indeed no js directory. Maybe a file just wasn't committed?

**Comment by jeregrine** [comment]
Thanks!
